import Link from "next/link";
import { notFound } from 'next/navigation';
import { getAllArticlePaths, getAllSections, getArticleByPath } from "../../../services/articleService";
import { getMetadata } from "../../../services/metadataService";
import ComingSoon from "../../../components/ComingSoon";
import CommandSnippet from "../../../components/CommandSnippet";
import Markdown from "../../../components/Markdown";
import MovedNotice from "../../../components/MovedNotice";
import DocsSidebar, { DocsSidebarMobile } from "../../../components/DocsSidebar";
import DocsBreadcrumb from "../../../components/DocsBreadcrumb";
import {
    formatSectionTitle,
    getVersionSwitcherEntries,
    orderSections,
} from "../../../services/versionService";

const dockerQuickRunCommand = `docker run -dt --name documentdb \\
  -p 10260:10260 \\
  ghcr.io/documentdb/documentdb/documentdb-local:latest \\
  --username <YOUR_USERNAME> \\
  --password <YOUR_PASSWORD>`;

const primerPrimaryLinkClass =
    "inline-flex w-full items-center justify-center rounded-md bg-blue-500 px-4 py-2 text-sm font-semibold text-white transition-colors hover:bg-blue-400 sm:w-auto";

const primerSecondaryLinkClass =
    "font-semibold text-blue-300 transition-colors hover:text-blue-200";

/**
 * Slugs under /docs/getting-started/ that no longer have their own content and
 * now point at the page that replaced them. Kept in one place so the metadata
 * and the rendered notice can never disagree about where a page went.
 */
const movedGettingStartedPages: Record<string, { href: string; title: string }> = {
    'prebuilt-packages': {
        href: '/docs/getting-started/packages',
        title: 'Linux Packages Quick Start',
    },
    'vscode-extension-guide': {
        href: '/docs/getting-started/vscode-quickstart',
        title: 'Visual Studio Code Quick Start',
    },
};

function getMovedPage(section: string, slug: string[]) {
    if (section !== 'getting-started') {
        return undefined;
    }

    return movedGettingStartedPages[slug[slug.length - 1] ?? ''];
}

export async function generateStaticParams() {
    const paths = getAllArticlePaths();

    return paths.map((path) => ({
        section: path.section,
        slug: path.slug,
    }));
}

interface PageProps {
    params: Promise<{
        section: string;
        slug?: string[];
    }>;
}

export async function generateMetadata({ params }: PageProps) {
    const { section, slug = [] } = await params;
    const movedPage = getMovedPage(section, slug);

    // These URLs stay reachable for old bookmarks and inbound links, but the
    // content is somewhere else now. Pointing crawlers at the replacement stops
    // the two copies from competing, and keeps them out of sitemap.xml, which
    // is generated by reading the robots directive out of the built HTML.
    if (movedPage) {
        return {
            title: `${movedPage.title} - DocumentDB Documentation`,
            description: `This page has moved to ${movedPage.title}.`,
            alternates: { canonical: movedPage.href.endsWith('/') ? movedPage.href : `${movedPage.href}/` },
            robots: { index: false, follow: true },
        };
    }

    const articleData = getArticleByPath(section, slug);

    if (!articleData) {
        return {
            title: 'Documentation - DocumentDB',
        };
    }

    const { frontmatter, navigation, file } = articleData;
    const selectedNavItem = navigation.find((item) => item.link.includes(file));
    const pageTitle = frontmatter.title || selectedNavItem?.title || section;

    return getMetadata({
        title: `${pageTitle} - DocumentDB Documentation`,
        description: frontmatter.description || '',
        path: slug.length > 0 ? `/docs/${section}/${slug.join('/')}/` : `/docs/${section}/`,
        type: 'article',
    });
}

export default async function ArticlePage({ params }: PageProps) {
    const { section, slug = [] } = await params;
    const movedPage = getMovedPage(section, slug);

    if (movedPage) {
        return <MovedNotice href={movedPage.href} title={movedPage.title} />;
    }

    const articleData = getArticleByPath(section, slug);

    if (!articleData) {
        return notFound();
    }

    const { content, frontmatter, navigation, file } = articleData;
    const selectedNavItem = navigation.find((item) =>
        item.link.includes(file)
    );

    // Use title from frontmatter if available, otherwise fall back to navigation title or section name
    const pageTitle = frontmatter.title || selectedNavItem?.title || section;
    const showInstallPrimer = section === "getting-started" && file === "index";
    const isComingSoon = frontmatter.layout === 'coming-soon';
    // coming-soon pages carry placeholder prose with no markdown heading, so
    // the h1 has to come from the frontmatter title - otherwise the page ships
    // with no heading element at all. Guarded in case a future coming-soon page
    // does start with one.
    const showComingSoonHeading = isComingSoon && !/^#\s/m.test(content);
    const sectionTitle = formatSectionTitle(section);

    // Pages of this section, rendered once and shared by the desktop sidebar
    // and the mobile disclosure.
    // For index files, match both /section and /section/index. For other files,
    // compare the final path segment exactly - a substring test marks every
    // sibling whose slug starts with this one (packages also matching
    // packages-operations).
    const navItems = navigation.map((item) => {
        const itemPath = item.link.replace('/docs/', '');
        const currentPath = file === 'index' ? section : `${section}/${file}`;
        const isActive = itemPath === currentPath ||
            (file === 'index' && itemPath === `${section}/index`) ||
            (file !== 'index' && item.link.split('/').pop() === file);

        return { title: item.title, href: item.link, active: isActive };
    });

    // Sibling sections, so a reader can cross to another section without
    // returning to the docs index first.
    const sectionItems = [
        ...orderSections(getAllSections()).map((s) => ({
            title: formatSectionTitle(s),
            href: `/docs/${s}`,
            active: s === section,
        })),
        { title: 'API Reference', href: '/docs/reference', active: false },
    ];

    const sidebarProps = {
        version: null,
        backHref: '/docs',
        backLabel: 'Back to Documentation',
        sectionTitle,
        nav: navItems,
        sections: sectionItems,
        switcherEntries: getVersionSwitcherEntries('current', section, file),
    };

    const breadcrumbs = file === 'index'
        ? [{ title: 'Docs', href: '/docs' }, { title: sectionTitle }]
        : [
            { title: 'Docs', href: '/docs' },
            { title: sectionTitle, href: `/docs/${section}` },
            { title: pageTitle },
        ];

    return (
        <div className="min-h-screen bg-neutral-900 relative overflow-hidden">
            {/* Background elements */}
            <div className="absolute inset-0 bg-gradient-to-br from-neutral-900 via-neutral-800 to-black"></div>
            <div className="absolute inset-0 opacity-5">
                <div className="absolute top-16 right-20 w-36 h-36 bg-blue-500 rounded-full blur-3xl animate-pulse"></div>
                <div
                    className="absolute bottom-20 left-16 w-28 h-28 bg-purple-500 rounded-full blur-3xl animate-pulse"
                    style={{ animationDelay: "1.5s" }}
                ></div>
            </div>

            <div className="relative flex min-h-screen">
                {/* Left Sidebar (desktop only; mobile gets the disclosure below) */}
                <DocsSidebar {...sidebarProps} />

                {/* Main Content */}
                <div className="flex-1 p-4 sm:p-8 overflow-y-auto">
                    <div className="max-w-4xl">
                        {/* Mobile section navigation */}
                        <DocsSidebarMobile {...sidebarProps} />

                        <DocsBreadcrumb crumbs={breadcrumbs} />

                        {/* Coming Soon Component for coming-soon layout */}
                        {showComingSoonHeading && (
                            <h1 className="text-4xl font-bold text-white mb-4">
                                {pageTitle}
                            </h1>
                        )}
                        {isComingSoon && <ComingSoon />}

                        {showInstallPrimer && (
                            <section className="mb-8 rounded-2xl border border-blue-500/30 bg-gradient-to-br from-blue-500/10 via-neutral-900/90 to-neutral-900/90 p-6">
                                <p className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-200">
                                    Recommended flow
                                </p>
                                <h2 className="mt-2 text-2xl font-semibold text-white">
                                    Install and verify DocumentDB
                                </h2>
                                <p className="mt-2 max-w-3xl text-sm leading-6 text-gray-300">
                                    Choose one install path first. After DocumentDB is running, verify the
                                    connection with mongosh before moving to a driver quick start.
                                </p>
                                <div className="mt-5 rounded-xl border border-neutral-800 bg-neutral-950/40 p-4">
                                    <div className="mb-4 flex items-start gap-3">
                                        <span className="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-blue-400/30 bg-blue-500/10 text-xs font-semibold text-blue-200">
                                            1
                                        </span>
                                        <div>
                                            <p className="text-sm font-semibold text-white">
                                                Choose an install path
                                            </p>
                                            <p className="mt-1 text-sm text-gray-400">
                                                Use Docker for the fastest local setup, or Linux packages for a
                                                persistent host installation.
                                            </p>
                                        </div>
                                    </div>
                                    <div className="grid gap-4 lg:grid-cols-2">
                                        <div className="rounded-xl border border-neutral-800 bg-neutral-900/70 p-4">
                                            <p className="text-sm font-semibold text-white">
                                                Run locally with Docker
                                            </p>
                                            <p className="mt-2 text-sm text-gray-400">
                                                Best for evaluation, local development, and quick testing.
                                            </p>
                                            <div className="mt-4">
                                                <CommandSnippet command={dockerQuickRunCommand} label="Docker" />
                                            </div>
                                            <div className="mt-4">
                                                <Link
                                                    href="/docs/getting-started/docker"
                                                    className={primerPrimaryLinkClass}
                                                >
                                                    Docker Quick Start
                                                </Link>
                                            </div>
                                        </div>
                                        <div className="rounded-xl border border-neutral-800 bg-neutral-900/70 p-4">
                                            <p className="text-sm font-semibold text-white">
                                                Install from Linux packages
                                            </p>
                                            <p className="mt-2 text-sm text-gray-400">
                                                Use the repository-backed package flow when you want a persistent
                                                server install. Generate the exact apt or rpm command with the{" "}
                                                <Link href="/packages" className={primerSecondaryLinkClass}>
                                                    Package Finder
                                                </Link>
                                                .
                                            </p>
                                            <div className="mt-4">
                                                <Link
                                                    href="/docs/getting-started/packages"
                                                    className={primerPrimaryLinkClass}
                                                >
                                                    Linux Packages Quick Start
                                                </Link>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="mt-4 rounded-xl border border-neutral-800 bg-neutral-950/40 p-4">
                                    <div className="flex items-start gap-3">
                                        <span className="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-full border border-blue-400/30 bg-blue-500/10 text-xs font-semibold text-blue-200">
                                            2
                                        </span>
                                        <div className="min-w-0">
                                            <p className="text-sm font-semibold text-white">
                                                Recommended: verify with mongosh
                                            </p>
                                            <p className="mt-1 text-sm text-gray-400">
                                                This is the fastest shared validation path after either install
                                                option because it confirms authentication, TLS, and a working
                                                endpoint before you add editor or driver setup. If you already
                                                know your target workflow, you can skip this and continue directly
                                                with VS Code or a driver quick start.
                                            </p>
                                            <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap sm:items-center sm:gap-4">
                                                <Link
                                                    href="/docs/getting-started/mongo-shell-quickstart"
                                                    className={primerPrimaryLinkClass}
                                                >
                                                    Mongo Shell Quick Start
                                                </Link>
                                                <p className="text-sm text-gray-400">
                                                    Or go directly to{" "}
                                                    <Link
                                                        href="/docs/getting-started/vscode-quickstart"
                                                        className={primerSecondaryLinkClass}
                                                    >
                                                        Visual Studio Code Quick Start
                                                    </Link>
                                                    ,{" "}
                                                    <Link
                                                        href="/docs/getting-started/nodejs-setup"
                                                        className={primerSecondaryLinkClass}
                                                    >
                                                        Node.js Quick Start
                                                    </Link>{" "}
                                                    or{" "}
                                                    <Link
                                                        href="/docs/getting-started/python-setup"
                                                        className={primerSecondaryLinkClass}
                                                    >
                                                        Python Quick Start
                                                    </Link>
                                                    .
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </section>
                        )}

                        {/* Markdown Content */}
                        <Markdown
                            content={content}
                            sourcePath={`/docs/${section}/${file}.md`}
                        />
                    </div>
                </div>
            </div>
        </div>
    );
}
